### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/MajiroStringEditor#1]

**Comment by marcussacana** [comment]
Should be hard, this tool has a very specifc use, I will need to rewrite the tool basically,
And since now I have a job I don't will have a free time for a while.

**Comment by Ileca** [comment]
If I understand correctly, this tool is used to edit .mjo in plain text, and doesn't help with de-encrypting them. Am I right?
I was searching for such program. Any idea if it exists? For Empress games too, like OP.

**Comment by marcussacana** [comment]
No, this can really be used to translate If you love me then say so, about alternatives... try this https://github.com/arcusmaximus/VNTranslationTools
